### ISSUE TITLE
Team leader

### ISSUE THREAD

**Issue by sokra** [webpack/analyse-tool#4]
We are looking for 2 - 3 team leaders for the analyse tool.

A team leader is responsible for reviewing, merging PRs and administrating the repo.

You should have at least some experience with git and open source on github.

@webpack/analyse-tool-team Please either apply yourself, propose someone or vote for somebody.

**Comment by abd124abd** [comment]
Happy to try to help if no one else would like to do this.  Am not a git expert but would take the role seriously.

If more knowledgeable participants come forward then please ignore.

EDIT: Ball got rolling it seems :).  Can ignore this then.  Nothing wrong with people stepping forward to express interest.

**Comment by jnwng** [comment]
i'd like to shamelessly nominate myself - as a front-end engineer here at coursera for the last couple of years, i've had the chance to:
- build user interfaces and learning experiences targeted towards learners of vastly different backgrounds
- take the technical lead / project management role on multiple projects (consisting of interfacing with product management, designers, as well as a small technical team)
- write and share my contributions in both a technical and non-technical scope

most recently, i've dedicated myself to improving the burgeoning front-end organization here at Coursera, focusing on not only increasing the efficiency of how our applications are delivered, but also empowering the front-end community here at Coursera. i strive to improve our stance around OSS as much as possible - the folks over @videojs/contributors have received most of the love.

while most of my work is not public, i've been using github for almost 4 years now, have seen the best and worst of communities on this platform, and hope that i can help contribute as much as i can to projects like webpack that are changing how developers work.

 i've also spent the last month or two modifying and transitioning our entire (~8k modules) set of applications over to webpack, a scale that you don't normally find in the examples and tutorials, giving me some interesting insights on what a more perfect analyse tool might provide to our project.

**Comment by timaschew** [comment]
I would like to volunteer.
I have experience in two open source projects: [js2coffee](https://github.com/js2coffee/js2coffee-v0-history) and [component](https://github.com/componentjs/component) where I lead the project for several months. In git I'm familiar with rebase in interactive mode, most for using fixup or sqaush and git submodules beside all the usual git commands.

We started to use webpack, redux at our company some months ago and currently I'm also working on an own project with this stack. I'm a big fan of HMR.

**Comment by bartekus** [comment]
I feel comfortable voting for and following all of the current volunteers. Furthermore I'm glad that so far, everybody that has step up to the position has expressed experience, interest and understanding of the bleeding edge technology that react, redux, babel and webpack allow. I also believe that we have an unique opportunity to fuze otherwise fragmented community by selecting best pieces for use in our project and setting an example/standard that we ourselves will follow and that by extension, so will others. I'm personally a big fan of react-starter-kit by KriaSoft which currently suffers from incomplete nature and use of unconventional routing solution. Then there is the lovely 3ree-stack and the redux real-world example implementation both of which I adore for their own reasons. So currently I'm trying to infuze react-starter-kit and the redux state overlay from real-world example into 3ree-stack which would make it the most complete, full-stack javascript solution on the market then adding react-native once it's 14.x ready and we'd have ourselves the next RoR/MEAN grade of a stack. Imagine that, all nicely tied with webpack and with our yet to be implemented vision, full analytical capability, from the health of dependencies all the way to current state and health of the deployed application

This my friends is not a dream, this is today's possibility and we have the front seats to bring it into the real world. 
Welcome to the world of Webpack Gentlemen, welcome to the Web Development of 2016 and beyond!

**Comment by alajmo** [comment]
Everything @Bartekus said, and I'd also like to propose we try to stick to as little config files as possible, It's enough having package.json / webpack.config.js in my humble opinion! Been experimenting with tape (for the testing) + webpack and it works really great, that's coming from heavy karma + jasmine config file!

But perhaps that's getting a bit ahead of ourselves, what's most important is we get the ball rolling so without doing any prior research except reading your posts, I vote for all the 3 self nominated candidates.

**Comment by sokra** [comment]
Teamleaders: @jnwng @timaschew
